### ISSUE TITLE
java.lang.ClassCastException: com.revenuecat.purchases.models.GoogleStoreProduct cannot be cast to io.shortway.kobankat.models.StoreProduct

### ISSUE THREAD

**Issue by Moozart** [JayShortway/kobankat#48] opened 2024-03-30 14:16 UTC
Hello,

When I use map like this in composeApp module 

`availablePackages.map { pack -> pack.product as StoreProduct}`

Throws java.lang.ClassCastException: com.revenuecat.purchases.models.GoogleStoreProduct cannot be cast to io.shortway.kobankat.models.StoreProduct

If don't add type casting, throws build time  error

Type mismatch: inferred type is com.revenuecat.purchases.models.StoreProduct but io.shortway.kobankat.models.StoreProduct was expected

Do you have any idea or advice.
Thanks to you for good libray

**Comment by JayShortway** [comment] 2024-03-31 00:32
Hi, thanks for flagging this!

If you don't add type casting, which target are you building that throws the build error? 
What's the reason for the cast? To attempt to fix the build error, or is there an additional reason? 

I'm currently on holiday so I can't try to reproduce it myself unfortunately.

**Comment by Moozart** [comment] 2024-03-31 08:49
Target Android has this error. IOS not. I just want to copy products in cacheStoreProductsList: List<StoreProduct> to purchase it via productId finding from cacheStoreProductList. Because I pass only Id to uiState. 

I changed my strategy after that crash. I used Package to purchase via identifier. There is no issue with Package

**Comment by Qw4z1** [comment] 2024-04-03 14:21
I'm also seeing `Type mismatch: inferred type is com.revenuecat.purchases.models.StoreProduct but io.shortway.kobankat.models.StoreProduct was expected` at compile time, even though I'm importing `io.shortway.kobankat.models.StoreProduct` and just call `offering.package.product` to get the StoreProduct.

Could it be [this line](https://github.com/JayShortway/kobankat/blob/main/core/src/androidMain/kotlin/io/shortway/kobankat/models/StoreProduct.android.kt#L10) that is confusing things?

**Comment by JayShortway** [comment] 2024-04-04 09:51
@Moozart Good to hear you found a workaround!
@Qw4z1 I think you might be right that that line is the culprit! Thanks for pinpointing it.

For some reason StoreProduct is not a type alias, while most other classes are. I'm not sure what the reason for that was anymore.

Since I'm currently on holiday, I'll be able to look at this in about 2 weeks or so.

**Comment by Qw4z1** [comment] 2024-04-04 10:23
@JayShortway No stress! You've done plenty already! =)

I might take a stab at it if I get time before you're back. Not my area of expertise, though, so no promises. 😅

**Comment by JayShortway** [comment] 2024-04-06 07:36
@Qw4z1 Oh yes, that's very welcome of course! Feel free to take a look if you have the time, but no worries if you don't.

**Comment by JayShortway** [comment] 2024-04-21 14:38
I have a reproducer which should be run on CI once #56 is merged, to prevent regressions. Haven't had time to think about a proper fix yet though.

**Comment by JayShortway** [comment] 2024-04-22 08:50
>For some reason StoreProduct is not a type alias, while most other classes are. I'm not sure what the reason for that was anymore.  
  
The reason for this is that the official SDK defines `StoreProduct` as an interface on Android, and as a class on iOS. Since the common definition in KobanKat is `expect class`, it's impossible to type-alias that to an interface. (It _is_ type aliased on iOS.) Changing the common definition to `expect interface` would inverse the situation, but I'm not sure yet if that's preferable.

**Comment by Qw4z1** [comment] 2024-04-22 09:16
Another way to solve it is to write wrapper classes instead of expect/actuals and expose `NativeXyz` interfaces from Android and IOS. It's not as elegant, but at least there is no shadowing. Works well in Firebase-kotlin-sdk.

**Comment by JayShortway** [comment] 2024-04-22 11:02
@Qw4z1 That's true! In general it's a good suggestion to look at firebase-kotlin-sdk for inspiration. However that's quite a big refactor. I think for now a more pragmatic solution would be to rename the `Package.product` field so as to not shadow the official SDK. 

@Moozart That means the field to get the `StoreProduct` from a `Package` will be called `storeProduct` (instead of `product`).

**Closed** 2024-04-22 11:25 UTC
